[tasks.default]
usage = '''
flag "--time-limit <time_limit>" help="Test time limit in seconds" default="15"
flag "--concurrency <concurrency>" help="Number of concurrent workers" default="10"
'''
run = "lein run -- test --nodes-file nodes --time-limit {{usage.time_limit}} --concurrency {{usage.concurrency}}"

[tasks.cleanup]
run = "rm -rf store/*"
