[tasks.default]
usage = 'flag "--time-limit <time_limit>" help="Test time limit in seconds" default="60"'
run = "lein run -- test --nodes-file nodes --time-limit ${usage_time_limit}"

[tasks.cleanup]
run = "rm -rf store/*"
